### ISSUE TITLE
Multi Action not Supported

### ISSUE THREAD

**Issue by kbirand** [shells-dw/StreamDeck-OSC#1]
I see that the plugin is not being maintained for 2 years but I still wanted to try my luck. I heavily depend on this plugin but when I try to put the plugin into a multi action, it is not available.

**Comment by shells-dw** [comment]
Hi Koray, I've had issues with other plugins and StreamDeck Multi Actions before and don't really use them myself, so I've disabled them by default.
Had a quick test to see if it would basically work and ... it seems like it does. No warranty though, as said these multi actions are acting a bit strange at times, at least for me.
I've pushed a new version to [here](https://github.com/shells-dw/StreamDeck-OSC/blob/master/Release/de.shells.osc.streamDeckPlugin), nothing else has changed except for the manifest.json entry that enables the plugin to be available in multi actions.
Hope it works for you :)
Cheers
