### ISSUE TITLE
Could not pass a 0 value as Int or Float 

### ISSUE THREAD

**Issue by tylerstraub** [shells-dw/StreamDeck-OSC#2]
The plugin was preventing me from passing a 0 as an int or float, not sure why.

That's all, cheers.

**Comment by shells-dw** [comment]
hm. Yeah, it should accept 0. I'll look into it when I got time. Most certainly a bug.

I'll keep you posted.

**Comment by shells-dw** [comment]
Fixed with [version 2.0.0 ](https://github.com/shells-dw/StreamDeck-OSC/releases/tag/v2.0.0)

Sorry it took me a while to dust this plugin ;)
