### ISSUE TITLE
Sending only integer parameter incorrectly sends float as well.

### ISSUE THREAD

**Issue by mykel** [shells-dw/StreamDeck-OSC#3]
In the case when only sendInt is set the application also sends the floatValue which can cause the receiver to not recognise the request.  Fix is removing the floatValue parameter on line 126 of PluginAction.cs

**Comment by shells-dw** [comment]
it did, fixed in [version 2.0.0](https://github.com/shells-dw/StreamDeck-OSC/releases/tag/v2.0.0)

Thanks for pointing me to the issue!
