### ISSUE TITLE
Default and Global IP/Port settings

### ISSUE THREAD

**Issue by drjedd** [shells-dw/StreamDeck-OSC#4]
Hello, and thanks for your work! (and fantastic implementation for the RME Totalmix by the way!)

In the interest of future-proofing and simplifying my Reaper Stream Deck profiles (which have about 500-600 of these OSC actions mapped to just as many buttons) I'm wondering if there's a way to either:

1) have the plugin send osc commands to the default (127.0.0.1:7001) values if these are not specified (currently it forces you to input values, leaving the field blank prompts "Please fill out this field" message.

2) specify somewhere (in a file or a special action using SetGlobalSettings) a new default or global IP/Port so it can be changed everywhere without having to fiddle with each action

Ideally both, allowing for some flexibility and making the whole thing more maintainable.

I'm not using osc on several devices but I guess for this use case you could even specify a list of devices with set IPs and ports, and then specify a default one. But that might be adding a lot of unnecessary complexity.

In any case, many thanks for your work!

**Comment by shells-dw** [comment]
Thanks buddy, much appreciated.
I just published [version 2.0.0](https://github.com/shells-dw/StreamDeck-OSC/releases/tag/v2.0.0)
This should address most issues the plugin had.

>     1. have the plugin send osc commands to the default (127.0.0.1:7001) values if these are not specified (currently it forces you to input values, leaving the field blank prompts "Please fill out this field" message.
> 
>     2. specify somewhere (in a file or a special action using SetGlobalSettings) a new default or global IP/Port so it can be changed everywhere without having to fiddle with each action
> 
Yeah, not sure what I was thinking. It now defaults to 127.0.0.1:7001 if nothing's entered, but you can change the default to reflect any custom preferences you might have with the [config file](https://github.com/shells-dw/StreamDeck-OSC#appsettingsjson)
This however only changes it for **new** buttons, existing ones will remain as they are. It doesn't seem to be very straight forward to change a setting for *all* buttons - especially when talking multiple hundred they are split across multiple pages, subpages and possibly even profiles... this just sounded like too much trouble to get into, honestly.
I opted against just overwriting plugin settings with the config file settings (at least IP and Port) for every button when it comes into focus (which is quite a lot easier to do) as this might mess up setups for users with multiple endpoints (obviously) and introducing a config flag... yeah maybe, if you ... *really* want that, I might think about it, but for now it's what it is ;)
I would assume it's probably easier to just make sure the IP your OSC controller is assigned does not change anyway.

check out the new version and let me know if it works for you.

**Comment by drjedd** [comment]
Hey there,

Yeah I'm able to work with that :)

In my case I'm always broadcasting locally so the IP will never change. But if we were thinking of more complex setups like a music studio with two computers or a really complex workflow it would be good to batch update all the ips at once.

That being said, there are solutions like Bitfocus Companion for these kind of situations. And I'm happy with your plugin as-is because I don't have to run Stream Deck services + companion (and map everything 1to1 between the two) just to send osc commands!

So thanks again for the quick release that made my life much easier while reworking my stream deck profiles!!
